[package]
name = "druid_gio_widgets"
version = "0.1.0"
edition = "2024"

[dependencies]
druid = { version = "0.8.3", features = ["im", "raw-win-handle"] }
tracing = "0.1.41"
cocoa = { version = "0.24.1" }
objc = "0.2.7"
